CREATE TABLE IF NOT EXISTS transaction_logs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    request_id VARCHAR(32) NOT NULL,
    session_id VARCHAR(128) NULL,
    user_id INT NULL,
    api_key_id INT NULL,
    method VARCHAR(10) NOT NULL,
    path VARCHAR(255) NOT NULL,
    controller VARCHAR(255) NULL,
    auth_mode VARCHAR(32) NOT NULL DEFAULT 'anonymous',
    is_authenticated TINYINT(1) DEFAULT 0,
    status_code INT NOT NULL,
    duration_ms INT NULL,
    validation_errors JSON NULL,
    request_payload JSON NULL,
    response_summary JSON NULL,
    error_message TEXT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transaction_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_transaction_logs_api_key FOREIGN KEY (api_key_id) REFERENCES api_keys(id) ON DELETE SET NULL,
    INDEX idx_transaction_logs_request_id (request_id),
    INDEX idx_transaction_logs_user (user_id),
    INDEX idx_transaction_logs_status (status_code),
    INDEX idx_transaction_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;